In [22]:
import statsmodels.api as sm
from statsmodels.discrete.discrete_model import Probit
import pandas as pd
import numpy as np
from scipy.stats import norm
from statsmodels import stats

In [23]:
df = pd.read_csv("probit_dataset.csv")
df

,heart,lungs,liver,kidneys,stomach,spine,diabetes,hypertension,joints,ENT_organs,...,mar_st,visit_doctor,work,alcohol,smoking,phys_active,region,is_health_good,is_health_very_good,diploma
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4593,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,142.0,0.0,0.0,0.0
4594,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,142.0,0.0,0.0,0.0
4595,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,77.0,0.0,0.0,0.0
4596,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,77.0,0.0,0.0,0.0
4597,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,77.0,1.0,0.0,1.0

In [24]:
df.columns

Index(['heart', 'lungs', 'liver', 'kidneys', 'stomach', 'spine', 'diabetes',
       'hypertension', 'joints', 'ENT_organs', 'neurology', 'eyes', 'allergy',
       'veins', 'skin', 'oncology', 'age', 'income', 'n_child', 'sex',
       'type_area', 'invalid', 'mar_st', 'visit_doctor', 'work', 'alcohol',
       'smoking', 'phys_active', 'region', 'is_health_good',
       'is_health_very_good', 'diploma'],
      dtype='str')

In [25]:

# 1. Создаём словарь "код региона -> значение alcohol_by_region 
# (Потребление алкогольной продукции на душу населения (в литрах этанола) для этого региона)"
alcohol_dict = {
    1: 96.13,
    9: 77.48,
    10: 124.47,
    12: 121.17,
    14: 102.76,
    33: 93.26,
    39: 86.51,
    45: 100.86,
    46: 132.27,
    47: 96.62,
    48: 109.46,
    52: 49.65,
    58: 109.66,
    66: 100.53,
    67: 106.43,
    70: 100.44,
    71: 111.83,
    72: 109.08,
    73: 100.53,
    77: 28.97,
    84: 109.66,
    86: 85.72,
    89: 146.86,
    92: 99.02,
    93: 113.16,
    100: 100.44,
    105: 146.86,
    106: 120.05,
    107: 120.05,
    116: 103.08,
    117: 139.63,
    129: 77.48,
    135: 109.62,
    136: 100.89,
    137: 63.11,
    138: 60.22,
    141: 80.65,
    142: 97.76,
    161: 104.41,
    200: 117.44
}

# 2. Создаём словарь "код региона -> значение smoking_by_region 
# (Объем легальных розничных продаж сигарет на душу совершеннолетнего населения для этого региона)"
smoking_dict = {
    1: 411,
    9: 402,
    10: 307,
    12: 379,
    14: 344,
    33: 295,
    39: 278,
    45: 294,
    46: 377,
    47: 327,
    48: 275,      
    52: 248,
    58: 337,
    66: 361,
    67: 398,
    70: 311,
    71: 432,
    72: 313,
    73: 361,
    77: 80,
    84: 337,
    86: 432,      
    89: 539,      
    92: 483,
    93: 549,
    100: 311,
    105: 539,
    106: 354,
    107: 354,
    116: 384,     
    117: 300,
    129: 402,
    135: 300,
    136: 334,
    137: 301,
    138: 257,
    141: 283,
    142: 458,
    161: 323,
    200: 309
}

# 3. Создаём словарь "код региона -> значение marriages_by_region 
# (Число зарегистрированных браков в расчете на 1000 населения (оперативные данные) для этого региона)"

marriage_dict = {
    1: 3.9,
    9: 7.3,
    10: 5.4,
    12: 6.1,
    14: 5.3,
    33: 5.3,
    39: 5.5,
    45: 5.9,
    46: 5.9,
    47: 6.1,
    48: 4.4,
    52: 5.1,
    58: 6.5,
    66: 6.7,
    67: 6.0,
    70: 5.5,
    71: 6.6,
    72: 5.5,
    73: 6.7,
    77: 4.6,
    84: 6.5,
    86: 5.7,
    89: 5.9,
    92: 8.0,
    93: 7.7,
    100: 5.5,
    105: 5.9,
    106: 6.5,
    107: 6.5,
    116: 6.1,
    117: 5.4,
    129: 7.3,
    135: 5.8,
    136: 5.5,
    137: 6.0,
    138: 6.6,
    141: 9.0,
    142: 5.5,
    161: 7.1,
    200: 6.3
}


# 3. Создаём словарь "код региона -> значение phys_activity_by_region 
# (Рейтинговый балл по приверженности населения ЗОЖ для этого региона)"
phys_dict = {
    1: 60.2,
    9: 81.7,
    10: 55.2,
    12: 55.8,
    14: 72.7,
    33: 76.2,
    39: 75.7,
    45: 70.2,
    46: 59.3,
    47: 64.6,
    48: 74.8,      
    52: 81.5,
    58: 67.8,
    66: 46.7,
    67: 62.7,
    70: 68.9,
    71: 63.1,
    72: 72.5,
    73: 46.7,
    77: 81.8,
    84: 67.8,
    86: 58.9,      
    89: 54.6,      
    92: 56.9,
    93: 53.3,
    100: 68.9,
    105: 54.6,
    106: 43.2,
    107: 43.2,
    116: 66.2,     
    117: 76.0,
    129: 81.7,
    135: 69.6,
    136: 81.5,
    137: 74.9,
    138: 76.0,
    141: 79.3,
    142: 80.1,
    161: 60.9,
    200: 60.1
}


df['alcohol_by_region'] = df['region'].map(alcohol_dict)
df['smoking_by_region'] = df['region'].map(smoking_dict)
df['marriages_by_region'] = df['region'].map(marriage_dict)
df['phys_activity_by_region'] = df['region'].map(phys_dict)

df

,heart,lungs,liver,kidneys,stomach,spine,diabetes,hypertension,joints,ENT_organs,...,smoking,phys_active,region,is_health_good,is_health_very_good,diploma,alcohol_by_region,smoking_by_region,marriages_by_region,phys_activity_by_region
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,96.13,411,3.9,60.2
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,96.13,411,3.9,60.2
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,96.13,411,3.9,60.2
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,96.13,411,3.9,60.2
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,96.13,411,3.9,60.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4593,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,142.0,0.0,0.0,0.0,97.76,458,5.5,80.1
4594,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,142.0,0.0,0.0,0.0,97.76,458,5.5,80.1
4595,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,77.0,0.0,0.0,0.0,28.97,80,4.6,81.8
4596,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,77.0,0.0,0.0,0.0,28.97,80,4.6,81.8
4597,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,77.0,1.0,0.0,1.0,28.97,80,4.6,81.8

In [26]:
df.columns

Index(['heart', 'lungs', 'liver', 'kidneys', 'stomach', 'spine', 'diabetes',
       'hypertension', 'joints', 'ENT_organs', 'neurology', 'eyes', 'allergy',
       'veins', 'skin', 'oncology', 'age', 'income', 'n_child', 'sex',
       'type_area', 'invalid', 'mar_st', 'visit_doctor', 'work', 'alcohol',
       'smoking', 'phys_active', 'region', 'is_health_good',
       'is_health_very_good', 'diploma', 'alcohol_by_region',
       'smoking_by_region', 'marriages_by_region', 'phys_activity_by_region'],
      dtype='str')

In [27]:

def control_function_2spm(sex, illness, df, endog_vars, exog_vars, instruments):

    df_sex = df[df['sex'] == sex].copy()
    outcome = illness
    
    resid_cols = []
    
    for var in endog_vars:
        instr_for_var = instruments.get(var, [])
        first_step_vars = exog_vars + instr_for_var
        
        X1 = sm.add_constant(df_sex[first_step_vars])
        y1 = df_sex[var]
        
        probit1 = Probit(y1, X1)
        res1 = probit1.fit(disp=0)
        

        xb = res1.predict(X1, linear=True)
        prob = norm.cdf(xb)
        phi = norm.pdf(xb)
        
        generalized_resid = np.where(y1 == 1, phi/prob, -phi/(1-prob))
        resid_name = f'{var}_gresid'
        df_sex[resid_name] = generalized_resid
        resid_cols.append(resid_name)
    
    
    X2_vars = exog_vars + endog_vars + resid_cols
    X2 = sm.add_constant(df_sex[X2_vars])
    y2 = df_sex[outcome]
    

    
    probit2 = Probit(y2, X2)
    res2 = probit2.fit(disp=0)
    
    resid_cols_in_model = [col for col in resid_cols if col in res2.params.index]
    if resid_cols_in_model:
        
        # Wald тест
        constraints = [f'{col}=0' for col in resid_cols_in_model]
        wald_test = res2.wald_test(constraints)
        exogeneity_pval = wald_test.pvalue
    else:
        exogeneity_pval = np.nan
    
    print(res2.summary())

    return {
        'coef_diploma': res2.params.get('diploma', np.nan),
        'pval_diploma': res2.pvalues.get('diploma', np.nan),
        'exogeneity_pval': exogeneity_pval,
        'n_obs': len(y2),
        'pseudo_r2': res2.prsquared
    }


sexes = [1, 2]
illnesses = ['heart', 'lungs', 'liver', 'kidneys', 'stomach', 'spine', 'diabetes',
       'hypertension', 'joints', 'ENT_organs', 'neurology', 'eyes', 'allergy',
       'veins', 'skin', 'oncology', 'is_health_good']

endog_vars = ['diploma', 'mar_st', 'alcohol', 'smoking', 'phys_active']
exog_vars = ['age', 'income', 'n_child', 'type_area', 'invalid', 'visit_doctor', 'work']
instruments = {
    'diploma': ['alcohol_by_region', 'smoking_by_region', 'marriages_by_region', 'phys_activity_by_region'],
    'mar_st': ['marriages_by_region'],
    'alcohol': ['alcohol_by_region'],
    'smoking': ['smoking_by_region'],
    'phys_active': ['phys_activity_by_region']
}

results = []
for sex in sexes:
    for illness in illnesses:
        res = control_function_2spm(sex, illness, df, endog_vars, exog_vars, instruments)
        results.append({'sex': sex, 'illness': illness, **res})

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(

                          Probit Regression Results
==============================================================================
Dep. Variable:                  heart   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                  0.1370
Time:                        14:18:24   Log-Likelihood:                -346.76
converged:                       True   LL-Null:                       -401.83
Covariance Type:            nonrobust   LLR p-value:                 4.237e-16
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0097      0.018      0.522      0.601      -0.027       0.046
income              5.378e-06    3.5e-06      1.538      0.124   -1.48e-06    1.22e-05
n_child               -0.1224      0.180     -0.678      0.498      -0.476       0.231
type_area              0.4301      0.550      0.781      0.435      -0.649       1.509
invalid                0.0795      0.708      0.112      0.911      -1.308       1.467
visit_doctor           0.4773      0.645      0.740      0.459      -0.787       1.742
work                   0.9695      4.424      0.219      0.827      -7.701       9.641
diploma               -0.9538      1.141     -0.836      0.403      -3.191       1.283
mar_st                 0.6611      1.331      0.497      0.619      -1.948       3.270
alcohol               -3.8168      1.859     -2.054      0.040      -7.459      -0.174
smoking               -1.7605      5.826     -0.302      0.763     -13.180       9.659
phys_active           -2.1503      1.484     -1.449      0.147      -5.058       0.758
diploma_gresid         0.7005      0.681      1.028      0.304      -0.635       2.036
mar_st_gresid         -0.3465      0.681     -0.509      0.611      -1.681       0.988
alcohol_gresid         2.1324      1.108      1.924      0.054      -0.040       4.305
smoking_gresid         1.2144      3.612      0.336      0.737      -5.866       8.294
phys_active_gresid     1.2363      0.853      1.449      0.147      -0.435       2.908
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:                  lungs   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.06142
Time:                        14:18:24   Log-Likelihood:                -360.79
converged:                       True   LL-Null:                       -384.40
Covariance Type:            nonrobust   LLR p-value:                 6.294e-05
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0091      0.020     -0.450      0.653      -0.049       0.031
income             -8.953e-06   5.84e-06     -1.533      0.125   -2.04e-05    2.49e-06
n_child               -0.2425      0.189     -1.282      0.200      -0.613       0.128
type_area             -1.5954      0.606     -2.632      0.008      -2.783      -0.407
invalid                1.9259      0.796      2.420      0.016       0.366       3.486
visit_doctor          -1.5238      0.740     -2.059      0.040      -2.975      -0.073
work                   6.4077      4.846      1.322      0.186      -3.090      15.905
diploma               -1.1567      1.840     -0.629      0.530      -4.763       2.449
mar_st                -2.3773      1.605     -1.481      0.139      -5.523       0.768
alcohol                3.9874      1.976      2.018      0.044       0.115       7.860
smoking              -14.0083      6.312     -2.219      0.026     -26.379      -1.637
phys_active            3.8141      1.745      2.186      0.029       0.394       7.235
diploma_gresid         0.6153      1.091      0.564      0.573      -1.524       2.754
mar_st_gresid          1.3115      0.857      1.530      0.126      -0.369       2.992
alcohol_gresid        -2.4650      1.168     -2.110      0.035      -4.754      -0.176
smoking_gresid         8.8367      3.923      2.253      0.024       1.149      16.525
phys_active_gresid    -2.2640      1.022     -2.214      0.027      -4.268      -0.260
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(

                          Probit Regression Results
==============================================================================
Dep. Variable:                  liver   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.08908
Time:                        14:18:24   Log-Likelihood:                -264.93
converged:                       True   LL-Null:                       -290.84
Covariance Type:            nonrobust   LLR p-value:                 1.172e-05
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0327      0.023      1.451      0.147      -0.011       0.077
income               2.64e-06   3.82e-06      0.690      0.490   -4.86e-06    1.01e-05
n_child                0.0380      0.210      0.181      0.856      -0.373       0.449
type_area              0.3268      0.641      0.510      0.610      -0.930       1.583
invalid                0.1377      0.853      0.161      0.872      -1.534       1.809
visit_doctor           0.5588      0.749      0.746      0.456      -0.910       2.027
work                  -5.0925      5.177     -0.984      0.325     -15.239       5.055
diploma               -0.4688      1.305     -0.359      0.719      -3.026       2.088
mar_st                -0.1584      1.345     -0.118      0.906      -2.795       2.479
alcohol               -0.0489      2.290     -0.021      0.983      -4.538       4.440
smoking                2.6464      6.750      0.392      0.695     -10.582      15.875
phys_active            0.3082      1.944      0.159      0.874      -3.502       4.119
diploma_gresid         0.3665      0.782      0.468      0.639      -1.167       1.900
mar_st_gresid         -0.1406      0.686     -0.205      0.838      -1.486       1.204
alcohol_gresid         0.0023      1.359      0.002      0.999      -2.661       2.666
smoking_gresid        -1.3852      4.185     -0.331      0.741      -9.588       6.818
phys_active_gresid    -0.3042      1.132     -0.269      0.788      -2.523       1.915
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:                kidneys   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.05253
Time:                        14:18:24   Log-Likelihood:                -233.31
converged:                       True   LL-Null:                       -246.24
Covariance Type:            nonrobust   LLR p-value:                   0.05591
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0019      0.023     -0.084      0.933      -0.048       0.044
income             -4.125e-07   4.05e-06     -0.102      0.919   -8.35e-06    7.52e-06
n_child               -0.0706      0.217     -0.325      0.745      -0.496       0.355
type_area             -0.1326      0.666     -0.199      0.842      -1.437       1.172
invalid                0.6068      0.881      0.689      0.491      -1.119       2.333
visit_doctor          -0.3363      0.778     -0.432      0.666      -1.862       1.189
work                   2.0988      5.653      0.371      0.710      -8.981      13.179
diploma               -0.2569      1.385     -0.185      0.853      -2.972       2.458
mar_st                -0.7433      2.112     -0.352      0.725      -4.883       3.396
alcohol               -1.1464      2.333     -0.491      0.623      -5.718       3.426
smoking               -4.8046      7.028     -0.684      0.494     -18.579       8.969
phys_active            0.6319      1.912      0.330      0.741      -3.116       4.380
diploma_gresid         0.0938      0.834      0.112      0.910      -1.541       1.728
mar_st_gresid          0.6160      1.109      0.555      0.579      -1.558       2.790
alcohol_gresid         0.6278      1.387      0.453      0.651      -2.091       3.347
smoking_gresid         3.1065      4.358      0.713      0.476      -5.435      11.648
phys_active_gresid    -0.3314      1.119     -0.296      0.767      -2.524       1.861
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:                stomach   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.03663
Time:                        14:18:24   Log-Likelihood:                -781.13
converged:                       True   LL-Null:                       -810.83
Covariance Type:            nonrobust   LLR p-value:                 6.595e-07
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0076      0.014      0.543      0.587      -0.020       0.035
income             -2.739e-07   3.23e-06     -0.085      0.932    -6.6e-06    6.05e-06
n_child                0.0073      0.131      0.056      0.955      -0.249       0.263
type_area              0.4680      0.411      1.138      0.255      -0.338       1.274
invalid               -0.4494      0.556     -0.809      0.419      -1.539       0.640
visit_doctor           0.2824      0.489      0.577      0.564      -0.676       1.241
work                   0.1019      3.297      0.031      0.975      -6.361       6.565
diploma                0.6143      1.057      0.581      0.561      -1.457       2.686
mar_st                -0.3080      0.965     -0.319      0.750      -2.200       1.584
alcohol               -2.3615      1.426     -1.655      0.098      -5.157       0.434
smoking                0.1955      4.327      0.045      0.964      -8.285       8.676
phys_active           -0.9246      1.137     -0.813      0.416      -3.153       1.304
diploma_gresid        -0.4139      0.635     -0.652      0.515      -1.659       0.831
mar_st_gresid          0.0549      0.491      0.112      0.911      -0.908       1.018
alcohol_gresid         1.3967      0.846      1.651      0.099      -0.261       3.055
smoking_gresid        -0.0327      2.689     -0.012      0.990      -5.303       5.238
phys_active_gresid     0.5446      0.662      0.823      0.410      -0.752       1.841
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(

                          Probit Regression Results
==============================================================================
Dep. Variable:                  spine   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.05352
Time:                        14:18:24   Log-Likelihood:                -750.75
converged:                       True   LL-Null:                       -793.20
Covariance Type:            nonrobust   LLR p-value:                 2.142e-11
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0236      0.014      1.703      0.089      -0.004       0.051
income             -2.725e-06   3.82e-06     -0.713      0.476   -1.02e-05    4.76e-06
n_child                0.0317      0.132      0.240      0.810      -0.227       0.291
type_area             -0.0989      0.428     -0.231      0.817      -0.938       0.740
invalid                0.4149      0.566      0.733      0.464      -0.695       1.525
visit_doctor           0.2387      0.516      0.463      0.644      -0.773       1.250
work                  -3.4014      3.331     -1.021      0.307      -9.930       3.127
diploma                1.0053      1.223      0.822      0.411      -1.392       3.403
mar_st                 1.1652      0.994      1.172      0.241      -0.784       3.114
alcohol               -0.2129      1.419     -0.150      0.881      -2.993       2.568
smoking                0.4025      4.438      0.091      0.928      -8.296       9.101
phys_active           -0.5492      1.115     -0.493      0.622      -2.735       1.636
diploma_gresid        -0.7699      0.732     -1.052      0.293      -2.205       0.665
mar_st_gresid         -0.5434      0.500     -1.086      0.277      -1.524       0.437
alcohol_gresid         0.0880      0.843      0.104      0.917      -1.565       1.741
smoking_gresid        -0.2818      2.759     -0.102      0.919      -5.689       5.126
phys_active_gresid     0.3712      0.644      0.577      0.564      -0.890       1.633
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:               diabetes   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                  0.1168
Time:                        14:18:25   Log-Likelihood:                -268.51
converged:                       True   LL-Null:                       -304.01
Covariance Type:            nonrobust   LLR p-value:                 6.662e-09
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0053      0.022     -0.246      0.806      -0.048       0.037
income              -4.95e-06   5.92e-06     -0.837      0.403   -1.65e-05    6.65e-06
n_child               -0.4053      0.213     -1.904      0.057      -0.822       0.012
type_area             -0.9099      0.674     -1.350      0.177      -2.231       0.411
invalid                2.2017      0.855      2.576      0.010       0.526       3.877
visit_doctor          -0.7270      0.796     -0.913      0.361      -2.288       0.834
work                   2.7779      5.180      0.536      0.592      -7.375      12.931
diploma                0.1760      1.848      0.095      0.924      -3.446       3.798
mar_st                 1.0111      1.677      0.603      0.546      -2.275       4.298
alcohol                2.8596      2.255      1.268      0.205      -1.560       7.280
smoking              -11.8673      6.882     -1.724      0.085     -25.356       1.622
phys_active           -1.3361      1.790     -0.746      0.456      -4.845       2.173
diploma_gresid        -0.0331      1.104     -0.030      0.976      -2.197       2.131
mar_st_gresid         -0.4134      0.866     -0.478      0.633      -2.110       1.283
alcohol_gresid        -1.7618      1.340     -1.315      0.189      -4.388       0.864
smoking_gresid         7.3249      4.265      1.717      0.086      -1.035      15.685
phys_active_gresid     0.6614      1.032      0.641      0.522      -1.361       2.684
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:           hypertension   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                  0.1466
Time:                        14:18:25   Log-Likelihood:                -802.97
converged:                       True   LL-Null:                       -940.89
Covariance Type:            nonrobust   LLR p-value:                 2.516e-49
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0555      0.014      4.092      0.000       0.029       0.082
income              3.251e-06   2.82e-06      1.153      0.249   -2.27e-06    8.78e-06
n_child                0.0486      0.128      0.378      0.705      -0.203       0.300
type_area              0.1940      0.404      0.480      0.631      -0.598       0.986
invalid                0.3836      0.540      0.710      0.478      -0.675       1.442
visit_doctor           0.8329      0.479      1.738      0.082      -0.106       1.772
work                  -6.7202      3.244     -2.071      0.038     -13.079      -0.362
diploma                0.1177      0.903      0.130      0.896      -1.653       1.888
mar_st                 1.0798      0.976      1.107      0.269      -0.833       2.992
alcohol                0.5390      1.387      0.389      0.698      -2.180       3.258
smoking                2.8512      4.271      0.668      0.504      -5.520      11.222
phys_active           -1.3700      1.116     -1.228      0.220      -3.557       0.817
diploma_gresid         0.0432      0.540      0.080      0.936      -1.015       1.101
mar_st_gresid         -0.5522      0.497     -1.112      0.266      -1.525       0.421
alcohol_gresid        -0.3499      0.824     -0.425      0.671      -1.965       1.265
smoking_gresid        -1.7885      2.654     -0.674      0.500      -6.989       3.412
phys_active_gresid     0.6483      0.644      1.007      0.314      -0.614       1.910
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)

                          Probit Regression Results
==============================================================================
Dep. Variable:                 joints   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                  0.1210
Time:                        14:18:25   Log-Likelihood:                -645.07
converged:                       True   LL-Null:                       -733.89
Covariance Type:            nonrobust   LLR p-value:                 2.508e-29
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0088      0.015      0.592      0.554      -0.020       0.038
income             -7.848e-06   4.92e-06     -1.596      0.110   -1.75e-05    1.79e-06
n_child               -0.2563      0.145     -1.769      0.077      -0.540       0.028
type_area             -0.1506      0.485     -0.311      0.756      -1.101       0.799
invalid                0.1984      0.626      0.317      0.751      -1.029       1.426
visit_doctor          -0.4924      0.586     -0.841      0.401      -1.640       0.656
work                   4.3722      3.584      1.220      0.222      -2.652      11.396
diploma                1.2679      1.499      0.846      0.398      -1.671       4.207
mar_st                 0.6756      1.026      0.658      0.510      -1.336       2.687
alcohol               -3.0131      1.557     -1.935      0.053      -6.064       0.038
smoking               -7.1814      4.907     -1.464      0.143     -16.798       2.436
phys_active           -1.5859      1.221     -1.298      0.194      -3.980       0.808
diploma_gresid        -0.7388      0.894     -0.826      0.409      -2.491       1.014
mar_st_gresid         -0.4129      0.521     -0.792      0.428      -1.434       0.608
alcohol_gresid         1.7144      0.928      1.847      0.065      -0.104       3.533
smoking_gresid         4.4632      3.048      1.464      0.143      -1.510      10.437
phys_active_gresid     0.9753      0.703      1.388      0.165      -0.402       2.353
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:             ENT_organs   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.06422
Time:                        14:18:25   Log-Likelihood:                -389.35
converged:                       True   LL-Null:                       -416.07
Covariance Type:            nonrobust   LLR p-value:                 6.402e-06
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0029      0.019     -0.155      0.877      -0.040       0.034
income             -5.241e-06   6.48e-06     -0.809      0.419   -1.79e-05    7.46e-06
n_child                0.2734      0.185      1.475      0.140      -0.090       0.637
type_area              0.9399      0.644      1.460      0.144      -0.322       2.202
invalid               -1.6945      0.868     -1.952      0.051      -3.396       0.007
visit_doctor           1.1340      0.759      1.494      0.135      -0.353       2.621
work                  -3.6924      4.472     -0.826      0.409     -12.458       5.074
diploma                3.3872      1.976      1.714      0.086      -0.486       7.260
mar_st                 0.8929      1.346      0.663      0.507      -1.746       3.532
alcohol               -4.8510      2.110     -2.299      0.021      -8.986      -0.716
smoking                7.6415      6.231      1.226      0.220      -4.571      19.854
phys_active           -3.6271      1.623     -2.235      0.025      -6.807      -0.447
diploma_gresid        -1.9830      1.190     -1.667      0.096      -4.315       0.349
mar_st_gresid         -0.5298      0.672     -0.788      0.431      -1.848       0.788
alcohol_gresid         2.9867      1.262      2.367      0.018       0.513       5.460
smoking_gresid        -4.6896      3.871     -1.211      0.226     -12.277       2.897
phys_active_gresid     2.0078      0.942      2.132      0.033       0.162       3.854
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:              neurology   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                  0.1560
Time:                        14:18:25   Log-Likelihood:                -222.60
converged:                       True   LL-Null:                       -263.74
Covariance Type:            nonrobust   LLR p-value:                 6.450e-11
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0366      0.025      1.494      0.135      -0.011       0.085
income              7.248e-09   8.27e-06      0.001      0.999   -1.62e-05    1.62e-05
n_child                0.3097      0.236      1.313      0.189      -0.152       0.772
type_area              1.0147      0.822      1.235      0.217      -0.596       2.625
invalid               -0.5830      1.024     -0.569      0.569      -2.590       1.424
visit_doctor           1.8525      0.984      1.882      0.060      -0.076       3.781
work                  -8.2775      5.955     -1.390      0.164     -19.948       3.393
diploma                2.9764      2.473      1.204      0.229      -1.870       7.823
mar_st                -3.6425      1.718     -2.120      0.034      -7.010      -0.275
alcohol                1.7052      2.787      0.612      0.541      -3.758       7.168
smoking               10.0554      8.033      1.252      0.211      -5.689      25.800
phys_active           -3.9717      1.786     -2.224      0.026      -7.472      -0.471
diploma_gresid        -1.6432      1.484     -1.108      0.268      -4.551       1.265
mar_st_gresid          1.6583      0.909      1.824      0.068      -0.124       3.440
alcohol_gresid        -1.0289      1.656     -0.621      0.534      -4.274       2.216
smoking_gresid        -6.1991      4.977     -1.246      0.213     -15.954       3.555
phys_active_gresid     2.4070      1.029      2.339      0.019       0.390       4.424
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(

                          Probit Regression Results
==============================================================================
Dep. Variable:                   eyes   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.06052
Time:                        14:18:25   Log-Likelihood:                -480.95
converged:                       True   LL-Null:                       -511.93
Covariance Type:            nonrobust   LLR p-value:                 2.440e-07
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0181      0.017      1.079      0.280      -0.015       0.051
income              -2.75e-07   3.57e-06     -0.077      0.939   -7.27e-06    6.72e-06
n_child               -0.0464      0.158     -0.294      0.769      -0.356       0.263
type_area              0.2871      0.501      0.573      0.566      -0.694       1.269
invalid                0.4454      0.674      0.661      0.509      -0.876       1.767
visit_doctor          -0.2006      0.589     -0.341      0.733      -1.355       0.954
work                  -1.3981      4.018     -0.348      0.728      -9.273       6.477
diploma                0.2456      1.149      0.214      0.831      -2.007       2.498
mar_st                -0.0422      1.318     -0.032      0.974      -2.626       2.541
alcohol                0.0632      1.782      0.035      0.972      -3.430       3.556
smoking               -2.1036      5.254     -0.400      0.689     -12.401       8.194
phys_active           -0.6346      1.382     -0.459      0.646      -3.343       2.073
diploma_gresid        -0.0216      0.686     -0.031      0.975      -1.366       1.323
mar_st_gresid          0.1035      0.680      0.152      0.879      -1.229       1.436
alcohol_gresid         0.0678      1.056      0.064      0.949      -2.002       2.137
smoking_gresid         1.2845      3.265      0.393      0.694      -5.114       7.683
phys_active_gresid     0.3902      0.801      0.487      0.626      -1.179       1.960
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:                allergy   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.02825
Time:                        14:18:25   Log-Likelihood:                -370.68
converged:                       True   LL-Null:                       -381.46
Covariance Type:            nonrobust   LLR p-value:                    0.1583
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0323      0.020     -1.599      0.110      -0.072       0.007
income             -1.373e-06   3.75e-06     -0.366      0.714   -8.73e-06    5.98e-06
n_child               -0.2083      0.187     -1.112      0.266      -0.576       0.159
type_area             -0.3217      0.577     -0.558      0.577      -1.452       0.809
invalid               -0.0554      0.826     -0.067      0.947      -1.675       1.564
visit_doctor          -0.3922      0.673     -0.583      0.560      -1.712       0.927
work                   5.0607      4.835      1.047      0.295      -4.415      14.536
diploma               -0.4111      1.224     -0.336      0.737      -2.811       1.989
mar_st                -0.9176      1.810     -0.507      0.612      -4.465       2.630
alcohol                0.5615      1.880      0.299      0.765      -3.122       4.245
smoking               -8.0960      6.130     -1.321      0.187     -20.110       3.918
phys_active           -0.8835      1.626     -0.543      0.587      -4.071       2.304
diploma_gresid         0.3095      0.738      0.420      0.675      -1.136       1.755
mar_st_gresid          0.5778      0.930      0.621      0.534      -1.245       2.401
alcohol_gresid        -0.3900      1.110     -0.351      0.725      -2.565       1.785
smoking_gresid         4.9537      3.809      1.301      0.193      -2.512      12.419
phys_active_gresid     0.4613      0.953      0.484      0.628      -1.407       2.330
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)

                          Probit Regression Results
==============================================================================
Dep. Variable:                  veins   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.07639
Time:                        14:18:25   Log-Likelihood:                -262.46
converged:                       True   LL-Null:                       -284.16
Covariance Type:            nonrobust   LLR p-value:                 0.0002418
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0405      0.022      1.871      0.061      -0.002       0.083
income              1.044e-06   4.48e-06      0.233      0.816   -7.74e-06    9.83e-06
n_child                0.1337      0.199      0.670      0.503      -0.257       0.525
type_area              0.5191      0.657      0.790      0.429      -0.768       1.807
invalid               -0.2633      0.897     -0.294      0.769      -2.021       1.494
visit_doctor           0.6653      0.762      0.873      0.382      -0.828       2.158
work                  -6.3724      5.046     -1.263      0.207     -16.263       3.518
diploma                0.5554      1.448      0.384      0.701      -2.282       3.393
mar_st                 0.8740      1.457      0.600      0.549      -1.982       3.730
alcohol               -2.2070      2.392     -0.923      0.356      -6.895       2.481
smoking                4.7493      6.692      0.710      0.478      -8.367      17.866
phys_active            0.5917      1.957      0.302      0.762      -3.243       4.427
diploma_gresid        -0.2783      0.870     -0.320      0.749      -1.983       1.427
mar_st_gresid         -0.4930      0.740     -0.666      0.505      -1.943       0.957
alcohol_gresid         1.3935      1.430      0.974      0.330      -1.409       4.196
smoking_gresid        -2.8284      4.149     -0.682      0.495     -10.961       5.304
phys_active_gresid    -0.4197      1.143     -0.367      0.713      -2.660       1.820
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:                   skin   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.06234
Time:                        14:18:25   Log-Likelihood:                -160.29
converged:                      False   LL-Null:                       -170.95
Covariance Type:            nonrobust   LLR p-value:                    0.1668
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0075      0.028     -0.268      0.789      -0.062       0.047
income              2.443e-07   5.02e-06      0.049      0.961    -9.6e-06    1.01e-05
n_child                0.1556      0.246      0.633      0.527      -0.327       0.638
type_area              0.1260      0.809      0.156      0.876      -1.460       1.711
invalid               -6.0288   1.05e+04     -0.001      1.000   -2.05e+04    2.05e+04
visit_doctor           0.1673      0.915      0.183      0.855      -1.625       1.960
work                   3.1369      6.797      0.462      0.644     -10.185      16.459
diploma                2.1437      1.666      1.286      0.198      -1.122       5.410
mar_st                -4.9694      2.705     -1.837      0.066     -10.271       0.332
alcohol               -0.3851      2.848     -0.135      0.892      -5.968       5.198
smoking               -1.7373      8.372     -0.208      0.836     -18.145      14.671
phys_active           -1.9946      2.273     -0.878      0.380      -6.449       2.460
diploma_gresid        -1.3525      1.016     -1.331      0.183      -3.345       0.639
mar_st_gresid          2.6303      1.443      1.822      0.068      -0.199       5.459
alcohol_gresid         0.1640      1.683      0.097      0.922      -3.135       3.463
smoking_gresid         1.0787      5.190      0.208      0.835      -9.094      11.251
phys_active_gresid     1.1846      1.334      0.888      0.375      -1.430       3.799
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)

                          Probit Regression Results
==============================================================================
Dep. Variable:               oncology   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                  0.3455
Time:                        14:18:26   Log-Likelihood:                -30.310
converged:                      False   LL-Null:                       -46.308
Covariance Type:            nonrobust   LLR p-value:                   0.01001
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0527      0.047     -1.125      0.261      -0.144       0.039
income             -2.135e-05   1.39e-05     -1.536      0.124   -4.86e-05    5.89e-06
n_child               -0.7046      0.444     -1.586      0.113      -1.576       0.166
type_area             -1.6153      1.310     -1.233      0.217      -4.182       0.952
invalid                3.5004      1.624      2.155      0.031       0.317       6.684
visit_doctor          -2.8954      1.703     -1.701      0.089      -6.232       0.442
work                  10.0183     10.734      0.933      0.351     -11.020      31.057
diploma                6.4261      4.302      1.494      0.135      -2.006      14.858
mar_st                 2.6184      2.453      1.067      0.286      -2.189       7.426
alcohol                3.4115      3.930      0.868      0.385      -4.291      11.114
smoking              -22.9278     14.471     -1.584      0.113     -51.290       5.434
phys_active           -9.7004      4.244     -2.285      0.022     -18.019      -1.381
diploma_gresid        -3.8284      2.573     -1.488      0.137      -8.872       1.215
mar_st_gresid         -1.3316      1.228     -1.084      0.278      -3.738       1.075
alcohol_gresid        -2.2063      2.347     -0.940      0.347      -6.807       2.394
smoking_gresid        14.3783      9.005      1.597      0.110      -3.272      32.029
phys_active_gresid     5.1909      2.216      2.342      0.019       0.847       9.535
======================================================================================

Possibly complete quasi-separation: A fraction 0.11 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
                          Probit Regression Results
==============================================================================
Dep. Variable:         is_health_good   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                  0.1269
Time:                        14:18:26   Log-Likelihood:                -1165.2
converged:                       True   LL-Null:                       -1334.5
Covariance Type:            nonrobust   LLR p-value:                 2.466e-62
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0106      0.012     -0.862      0.389      -0.035       0.013
income              4.545e-06   3.23e-06      1.405      0.160   -1.79e-06    1.09e-05
n_child                0.1249      0.117      1.069      0.285      -0.104       0.354
type_area             -0.0663      0.373     -0.178      0.859      -0.797       0.665
invalid               -1.4523      0.633     -2.294      0.022      -2.693      -0.212
visit_doctor          -0.0803      0.452     -0.178      0.859      -0.966       0.805
work                  -3.9866      2.942     -1.355      0.175      -9.753       1.780
diploma               -0.2549      1.004     -0.254      0.800      -2.223       1.714
mar_st                 0.0232      0.917      0.025      0.980      -1.774       1.820
alcohol                1.9194      1.229      1.562      0.118      -0.489       4.328
smoking                4.9838      3.907      1.275      0.202      -2.675      12.642
phys_active            1.7633      0.970      1.819      0.069      -0.137       3.664
diploma_gresid         0.1444      0.599      0.241      0.810      -1.031       1.319
mar_st_gresid          0.0179      0.462      0.039      0.969      -0.887       0.922
alcohol_gresid        -1.0767      0.725     -1.485      0.138      -2.498       0.345
smoking_gresid        -3.1317      2.433     -1.287      0.198      -7.901       1.637
phys_active_gresid    -0.7997      0.564     -1.418      0.156      -1.905       0.305
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)

                          Probit Regression Results
==============================================================================
Dep. Variable:                  heart   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                  0.1261
Time:                        14:18:26   Log-Likelihood:                -403.55
converged:                       True   LL-Null:                       -461.76
Covariance Type:            nonrobust   LLR p-value:                 2.684e-17
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0539      0.018      3.002      0.003       0.019       0.089
income              9.229e-07   7.97e-06      0.116      0.908   -1.47e-05    1.65e-05
n_child               -0.0938      0.162     -0.579      0.562      -0.411       0.224
type_area             -0.0811      0.238     -0.341      0.733      -0.547       0.384
invalid                1.1204      0.366      3.065      0.002       0.404       1.837
visit_doctor           0.0695      0.163      0.426      0.670      -0.250       0.389
work                  -4.5774      1.480     -3.093      0.002      -7.478      -1.677
diploma               -0.6899      1.255     -0.550      0.583      -3.150       1.770
mar_st                 1.5156      1.227      1.235      0.217      -0.890       3.921
alcohol               -0.9475      0.913     -1.038      0.299      -2.737       0.842
smoking               -0.9262      1.640     -0.565      0.572      -4.140       2.287
phys_active            1.2425      1.801      0.690      0.490      -2.287       4.772
diploma_gresid         0.4030      0.769      0.524      0.600      -1.104       1.910
mar_st_gresid         -0.9652      0.738     -1.308      0.191      -2.411       0.481
alcohol_gresid         0.4342      0.560      0.776      0.438      -0.663       1.531
smoking_gresid         0.4661      0.901      0.517      0.605      -1.299       2.232
phys_active_gresid    -0.5555      1.032     -0.538      0.590      -2.578       1.467
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:                  lungs   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.05953
Time:                        14:18:26   Log-Likelihood:                -574.69
converged:                       True   LL-Null:                       -611.07
Covariance Type:            nonrobust   LLR p-value:                 3.269e-09
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0150      0.014      1.040      0.298      -0.013       0.043
income              2.302e-07   7.33e-06      0.031      0.975   -1.41e-05    1.46e-05
n_child                0.0170      0.127      0.134      0.893      -0.232       0.266
type_area              0.3232      0.218      1.486      0.137      -0.103       0.750
invalid                0.0934      0.369      0.253      0.800      -0.629       0.816
visit_doctor           0.1680      0.147      1.143      0.253      -0.120       0.456
work                  -2.2763      1.209     -1.883      0.060      -4.645       0.093
diploma               -0.2882      1.135     -0.254      0.800      -2.513       1.936
mar_st                 0.1786      1.004      0.178      0.859      -1.789       2.146
alcohol                0.3098      0.825      0.376      0.707      -1.307       1.926
smoking               -2.5506      1.323     -1.928      0.054      -5.144       0.043
phys_active           -0.9134      1.635     -0.559      0.576      -4.117       2.291
diploma_gresid        -0.0461      0.697     -0.066      0.947      -1.412       1.320
mar_st_gresid         -0.1143      0.601     -0.190      0.849      -1.293       1.064
alcohol_gresid        -0.1555      0.506     -0.308      0.758      -1.147       0.836
smoking_gresid         1.4753      0.729      2.023      0.043       0.046       2.904
phys_active_gresid     0.6147      0.941      0.653      0.514      -1.230       2.459
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)

                          Probit Regression Results
==============================================================================
Dep. Variable:                  liver   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.08348
Time:                        14:18:26   Log-Likelihood:                -351.50
converged:                       True   LL-Null:                       -383.51
Covariance Type:            nonrobust   LLR p-value:                 1.079e-07
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0848      0.022      3.881      0.000       0.042       0.128
income             -2.467e-06   9.51e-06     -0.260      0.795   -2.11e-05    1.62e-05
n_child               -0.4198      0.205     -2.044      0.041      -0.822      -0.017
type_area             -0.2234      0.262     -0.851      0.395      -0.738       0.291
invalid                0.4349      0.465      0.936      0.349      -0.476       1.345
visit_doctor           0.1187      0.171      0.693      0.488      -0.217       0.454
work                  -7.1375      1.781     -4.007      0.000     -10.629      -3.646
diploma                0.9430      1.504      0.627      0.531      -2.005       3.891
mar_st                 3.2426      1.490      2.176      0.030       0.322       6.164
alcohol               -1.0501      0.999     -1.051      0.293      -3.009       0.908
smoking                0.6580      1.572      0.418      0.676      -2.424       3.740
phys_active           -0.1636      1.885     -0.087      0.931      -3.858       3.531
diploma_gresid        -0.6198      0.923     -0.672      0.502      -2.429       1.189
mar_st_gresid         -2.0200      0.895     -2.258      0.024      -3.774      -0.266
alcohol_gresid         0.6794      0.615      1.104      0.269      -0.526       1.885
smoking_gresid        -0.2910      0.872     -0.334      0.739      -2.000       1.418
phys_active_gresid     0.1936      1.081      0.179      0.858      -1.925       2.312
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:                kidneys   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.04335
Time:                        14:18:26   Log-Likelihood:                -536.33
converged:                       True   LL-Null:                       -560.64
Covariance Type:            nonrobust   LLR p-value:                 3.807e-05
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0120      0.014     -0.878      0.380      -0.039       0.015
income             -3.052e-06   6.38e-06     -0.478      0.632   -1.56e-05    9.45e-06
n_child                0.2275      0.110      2.076      0.038       0.013       0.442
type_area             -0.0307      0.213     -0.144      0.886      -0.448       0.387
invalid                0.3409      0.314      1.085      0.278      -0.275       0.957
visit_doctor           0.2421      0.151      1.602      0.109      -0.054       0.538
work                  -0.6564      1.136     -0.578      0.564      -2.884       1.571
diploma               -0.6347      0.923     -0.688      0.492      -2.443       1.174
mar_st                -1.3205      0.908     -1.454      0.146      -3.101       0.460
alcohol               -0.0460      0.829     -0.055      0.956      -1.671       1.579
smoking               -0.7439      1.305     -0.570      0.569      -3.301       1.814
phys_active            2.2944      1.682      1.364      0.173      -1.003       5.591
diploma_gresid         0.2300      0.567      0.406      0.685      -0.880       1.340
mar_st_gresid          0.7311      0.542      1.349      0.177      -0.331       1.794
alcohol_gresid         0.0143      0.507      0.028      0.978      -0.979       1.008
smoking_gresid         0.4033      0.726      0.555      0.579      -1.020       1.827
phys_active_gresid    -1.2728      0.979     -1.300      0.194      -3.191       0.646
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(

                          Probit Regression Results
==============================================================================
Dep. Variable:                stomach   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.06684
Time:                        14:18:26   Log-Likelihood:                -1110.8
converged:                       True   LL-Null:                       -1190.4
Covariance Type:            nonrobust   LLR p-value:                 1.217e-25
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0402      0.011      3.627      0.000       0.018       0.062
income              5.636e-06   5.05e-06      1.117      0.264   -4.25e-06    1.55e-05
n_child               -0.1829      0.098     -1.865      0.062      -0.375       0.009
type_area              0.4869      0.163      2.989      0.003       0.168       0.806
invalid                0.5559      0.267      2.082      0.037       0.033       1.079
visit_doctor           0.4058      0.112      3.609      0.000       0.185       0.626
work                  -3.2369      0.918     -3.524      0.000      -5.037      -1.437
diploma               -0.0596      0.727     -0.082      0.935      -1.485       1.366
mar_st                 1.2957      0.753      1.721      0.085      -0.180       2.771
alcohol               -1.4107      0.619     -2.280      0.023      -2.623      -0.198
smoking                0.3211      0.936      0.343      0.732      -1.514       2.156
phys_active           -1.0219      1.272     -0.804      0.422      -3.514       1.470
diploma_gresid         0.0021      0.447      0.005      0.996      -0.874       0.878
mar_st_gresid         -0.8883      0.449     -1.980      0.048      -1.767      -0.009
alcohol_gresid         0.8764      0.379      2.313      0.021       0.134       1.619
smoking_gresid        -0.1651      0.522     -0.316      0.752      -1.188       0.858
phys_active_gresid     0.5623      0.738      0.762      0.446      -0.884       2.009
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:                  spine   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.05867
Time:                        14:18:26   Log-Likelihood:                -1032.0
converged:                       True   LL-Null:                       -1096.3
Covariance Type:            nonrobust   LLR p-value:                 1.178e-19
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0242      0.011      2.176      0.030       0.002       0.046
income             -3.576e-07   5.24e-06     -0.068      0.946   -1.06e-05    9.91e-06
n_child               -0.0551      0.097     -0.566      0.571      -0.246       0.136
type_area             -0.1380      0.160     -0.865      0.387      -0.451       0.175
invalid                0.5791      0.268      2.158      0.031       0.053       1.105
visit_doctor           0.3882      0.109      3.546      0.000       0.174       0.603
work                  -2.0222      0.930     -2.174      0.030      -3.845      -0.199
diploma                0.6689      0.790      0.847      0.397      -0.879       2.217
mar_st                -0.0727      0.774     -0.094      0.925      -1.590       1.445
alcohol               -0.6077      0.616     -0.986      0.324      -1.816       0.600
smoking                0.6434      0.964      0.667      0.505      -1.247       2.534
phys_active           -1.0427      1.180     -0.884      0.377      -3.355       1.270
diploma_gresid        -0.4985      0.483     -1.031      0.303      -1.446       0.449
mar_st_gresid          0.0106      0.463      0.023      0.982      -0.897       0.918
alcohol_gresid         0.3603      0.379      0.951      0.341      -0.382       1.103
smoking_gresid        -0.3822      0.538     -0.711      0.477      -1.437       0.672
phys_active_gresid     0.7386      0.680      1.087      0.277      -0.593       2.071
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(

                          Probit Regression Results
==============================================================================
Dep. Variable:               diabetes   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                  0.1083
Time:                        14:18:27   Log-Likelihood:                -658.17
converged:                       True   LL-Null:                       -738.11
Covariance Type:            nonrobust   LLR p-value:                 8.695e-26
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0288      0.015      1.957      0.050   -3.73e-05       0.058
income              -6.96e-06   6.59e-06     -1.056      0.291   -1.99e-05    5.96e-06
n_child                0.1449      0.125      1.158      0.247      -0.100       0.390
type_area             -0.0519      0.194     -0.267      0.789      -0.432       0.328
invalid               -0.0870      0.325     -0.268      0.789      -0.724       0.550
visit_doctor           0.1935      0.134      1.442      0.149      -0.069       0.456
work                  -2.2700      1.222     -1.858      0.063      -4.665       0.125
diploma                1.7519      0.976      1.795      0.073      -0.161       3.665
mar_st                -1.3782      1.019     -1.352      0.176      -3.376       0.620
alcohol               -0.5689      0.774     -0.735      0.462      -2.085       0.947
smoking               -0.2246      1.203     -0.187      0.852      -2.583       2.134
phys_active           -0.4657      1.486     -0.313      0.754      -3.377       2.446
diploma_gresid        -1.1620      0.596     -1.950      0.051      -2.330       0.006
mar_st_gresid          0.7862      0.618      1.272      0.204      -0.426       1.998
alcohol_gresid         0.3823      0.474      0.806      0.420      -0.548       1.312
smoking_gresid         0.1525      0.665      0.229      0.819      -1.152       1.457
phys_active_gresid     0.3652      0.856      0.427      0.670      -1.312       2.042
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:           hypertension   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                  0.1765
Time:                        14:18:27   Log-Likelihood:                -1186.0
converged:                       True   LL-Null:                       -1440.3
Covariance Type:            nonrobust   LLR p-value:                 5.297e-98
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0721      0.011      6.600      0.000       0.051       0.093
income             -8.818e-06   5.07e-06     -1.739      0.082   -1.88e-05    1.12e-06
n_child                0.0894      0.091      0.978      0.328      -0.090       0.269
type_area             -0.2553      0.155     -1.650      0.099      -0.558       0.048
invalid                0.5777      0.274      2.108      0.035       0.041       1.115
visit_doctor           0.3631      0.104      3.477      0.001       0.158       0.568
work                  -4.9028      0.905     -5.417      0.000      -6.677      -3.129
diploma                1.4050      0.759      1.850      0.064      -0.083       2.893
mar_st                 0.5373      0.735      0.731      0.465      -0.903       1.978
alcohol               -0.3673      0.591     -0.621      0.534      -1.526       0.791
smoking                0.2541      0.948      0.268      0.789      -1.604       2.112
phys_active           -0.0673      1.208     -0.056      0.956      -2.435       2.301
diploma_gresid        -0.9331      0.465     -2.005      0.045      -1.845      -0.021
mar_st_gresid         -0.3690      0.441     -0.836      0.403      -1.234       0.496
alcohol_gresid         0.2538      0.362      0.700      0.484      -0.456       0.964
smoking_gresid        -0.2000      0.527     -0.379      0.705      -1.234       0.834
phys_active_gresid    -0.0486      0.696     -0.070      0.944      -1.413       1.316
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)

                          Probit Regression Results
==============================================================================
Dep. Variable:                 joints   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                  0.1556
Time:                        14:18:27   Log-Likelihood:                -1007.9
converged:                       True   LL-Null:                       -1193.7
Covariance Type:            nonrobust   LLR p-value:                 3.388e-69
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0607      0.012      4.972      0.000       0.037       0.085
income              3.522e-06   5.53e-06      0.637      0.524   -7.31e-06    1.44e-05
n_child               -0.1742      0.109     -1.591      0.112      -0.389       0.040
type_area              0.1435      0.168      0.853      0.393      -0.186       0.473
invalid                0.9988      0.283      3.530      0.000       0.444       1.553
visit_doctor           0.5943      0.114      5.195      0.000       0.370       0.819
work                  -3.7792      1.009     -3.744      0.000      -5.758      -1.801
diploma                0.5636      0.823      0.685      0.493      -1.049       2.177
mar_st                 0.9461      0.849      1.115      0.265      -0.717       2.609
alcohol               -1.7399      0.637     -2.732      0.006      -2.988      -0.492
smoking                0.6843      1.016      0.673      0.501      -1.308       2.676
phys_active           -1.9012      1.307     -1.455      0.146      -4.463       0.661
diploma_gresid        -0.4838      0.504     -0.960      0.337      -1.471       0.503
mar_st_gresid         -0.5202      0.511     -1.018      0.309      -1.522       0.481
alcohol_gresid         1.0238      0.391      2.619      0.009       0.258       1.790
smoking_gresid        -0.3617      0.564     -0.642      0.521      -1.466       0.743
phys_active_gresid     1.1204      0.753      1.487      0.137      -0.356       2.597
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:             ENT_organs   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.01811
Time:                        14:18:27   Log-Likelihood:                -778.92
converged:                       True   LL-Null:                       -793.29
Covariance Type:            nonrobust   LLR p-value:                   0.02575
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0110      0.012      0.892      0.372      -0.013       0.035
income              5.462e-06   5.77e-06      0.947      0.344   -5.85e-06    1.68e-05
n_child               -0.1235      0.106     -1.168      0.243      -0.331       0.084
type_area              0.1176      0.182      0.646      0.518      -0.239       0.474
invalid                0.3883      0.310      1.255      0.210      -0.218       0.995
visit_doctor           0.2418      0.125      1.938      0.053      -0.003       0.486
work                  -0.8920      1.031     -0.865      0.387      -2.913       1.129
diploma               -0.0450      0.844     -0.053      0.957      -1.700       1.610
mar_st                 0.3204      0.852      0.376      0.707      -1.350       1.990
alcohol               -2.5548      0.696     -3.673      0.000      -3.918      -1.192
smoking                2.0156      1.052      1.916      0.055      -0.046       4.077
phys_active           -0.5406      1.390     -0.389      0.697      -3.265       2.184
diploma_gresid        -0.0352      0.517     -0.068      0.946      -1.049       0.978
mar_st_gresid         -0.1624      0.507     -0.321      0.749      -1.155       0.831
alcohol_gresid         1.5651      0.428      3.654      0.000       0.726       2.405
smoking_gresid        -1.0536      0.589     -1.788      0.074      -2.209       0.101
phys_active_gresid     0.3450      0.804      0.429      0.668      -1.230       1.920
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)

                          Probit Regression Results
==============================================================================
Dep. Variable:              neurology   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.07153
Time:                        14:18:27   Log-Likelihood:                -431.64
converged:                       True   LL-Null:                       -464.89
Covariance Type:            nonrobust   LLR p-value:                 4.048e-08
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0255      0.017      1.505      0.132      -0.008       0.059
income              6.047e-06   6.92e-06      0.874      0.382   -7.52e-06    1.96e-05
n_child               -0.1157      0.150     -0.770      0.441      -0.410       0.179
type_area              0.0092      0.236      0.039      0.969      -0.453       0.471
invalid                0.6580      0.359      1.833      0.067      -0.046       1.362
visit_doctor           0.3631      0.167      2.175      0.030       0.036       0.690
work                  -3.5207      1.412     -2.493      0.013      -6.288      -0.753
diploma               -0.7541      1.016     -0.742      0.458      -2.745       1.237
mar_st                 0.9820      1.149      0.854      0.393      -1.271       3.235
alcohol                0.2096      0.896      0.234      0.815      -1.546       1.965
smoking               -1.9106      1.422     -1.344      0.179      -4.697       0.876
phys_active            0.2349      1.747      0.134      0.893      -3.190       3.659
diploma_gresid         0.4519      0.624      0.724      0.469      -0.772       1.675
mar_st_gresid         -0.6841      0.686     -0.997      0.319      -2.028       0.660
alcohol_gresid        -0.1320      0.548     -0.241      0.810      -1.206       0.942
smoking_gresid         1.2015      0.784      1.533      0.125      -0.335       2.738
phys_active_gresid    -0.0051      1.012     -0.005      0.996      -1.988       1.978
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:                   eyes   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.05640
Time:                        14:18:27   Log-Likelihood:                -942.58
converged:                       True   LL-Null:                       -998.92
Covariance Type:            nonrobust   LLR p-value:                 1.385e-16
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0537      0.012      4.427      0.000       0.030       0.077
income               4.97e-06   5.14e-06      0.967      0.333    -5.1e-06     1.5e-05
n_child               -0.3011      0.108     -2.788      0.005      -0.513      -0.089
type_area              0.3099      0.174      1.780      0.075      -0.031       0.651
invalid                1.1270      0.272      4.146      0.000       0.594       1.660
visit_doctor           0.0486      0.118      0.412      0.680      -0.183       0.280
work                  -4.0979      1.001     -4.095      0.000      -6.059      -2.137
diploma               -0.2202      0.733     -0.300      0.764      -1.658       1.217
mar_st                 2.1591      0.821      2.631      0.009       0.551       3.768
alcohol               -2.4588      0.649     -3.787      0.000      -3.731      -1.186
smoking                2.1226      0.967      2.196      0.028       0.228       4.017
phys_active            1.1149      1.311      0.850      0.395      -1.455       3.685
diploma_gresid         0.1625      0.451      0.361      0.718      -0.721       1.046
mar_st_gresid         -1.3311      0.489     -2.723      0.006      -2.289      -0.373
alcohol_gresid         1.4775      0.397      3.720      0.000       0.699       2.256
smoking_gresid        -1.1244      0.542     -2.076      0.038      -2.186      -0.063
phys_active_gresid    -0.5289      0.761     -0.695      0.487      -2.020       0.963
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)

                          Probit Regression Results
==============================================================================
Dep. Variable:                allergy   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.03957
Time:                        14:18:27   Log-Likelihood:                -725.30
converged:                       True   LL-Null:                       -755.18
Covariance Type:            nonrobust   LLR p-value:                 5.744e-07
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0279      0.013      2.077      0.038       0.002       0.054
income              5.047e-06   5.67e-06      0.890      0.373   -6.06e-06    1.62e-05
n_child               -0.2379      0.120     -1.989      0.047      -0.472      -0.003
type_area              0.0786      0.191      0.412      0.681      -0.296       0.453
invalid                0.6537      0.307      2.127      0.033       0.051       1.256
visit_doctor           0.3200      0.133      2.414      0.016       0.060       0.580
work                  -3.5448      1.125     -3.150      0.002      -5.750      -1.339
diploma                0.6451      0.800      0.806      0.420      -0.923       2.213
mar_st                 1.5308      0.931      1.645      0.100      -0.294       3.355
alcohol               -0.7076      0.721     -0.982      0.326      -2.120       0.705
smoking                0.3386      1.121      0.302      0.763      -1.859       2.537
phys_active           -0.9338      1.395     -0.669      0.503      -3.669       1.801
diploma_gresid        -0.4477      0.491     -0.912      0.362      -1.410       0.514
mar_st_gresid         -0.9012      0.554     -1.626      0.104      -1.988       0.185
alcohol_gresid         0.3679      0.440      0.837      0.403      -0.494       1.229
smoking_gresid        -0.2049      0.629     -0.326      0.745      -1.438       1.028
phys_active_gresid     0.7255      0.810      0.896      0.371      -0.862       2.313
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:                  veins   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.06246
Time:                        14:18:27   Log-Likelihood:                -813.96
converged:                       True   LL-Null:                       -868.18
Covariance Type:            nonrobust   LLR p-value:                 8.820e-16
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0583      0.013      4.445      0.000       0.033       0.084
income              7.001e-06   5.41e-06      1.295      0.195   -3.59e-06    1.76e-05
n_child               -0.2831      0.115     -2.456      0.014      -0.509      -0.057
type_area              0.2017      0.179      1.127      0.260      -0.149       0.552
invalid                0.6901      0.303      2.274      0.023       0.095       1.285
visit_doctor           0.1751      0.125      1.400      0.162      -0.070       0.420
work                  -5.7158      1.091     -5.241      0.000      -7.853      -3.578
diploma               -1.1821      0.802     -1.473      0.141      -2.755       0.390
mar_st                 2.6669      0.884      3.018      0.003       0.935       4.399
alcohol                0.3665      0.700      0.524      0.601      -1.005       1.738
smoking               -0.0494      1.034     -0.048      0.962      -2.075       1.977
phys_active           -0.0198      1.371     -0.014      0.989      -2.707       2.668
diploma_gresid         0.5886      0.493      1.194      0.232      -0.378       1.555
mar_st_gresid         -1.6208      0.528     -3.071      0.002      -2.655      -0.587
alcohol_gresid        -0.1934      0.427     -0.453      0.651      -1.031       0.644
smoking_gresid         0.1331      0.577      0.231      0.818      -0.998       1.264
phys_active_gresid     0.1519      0.792      0.192      0.848      -1.400       1.703
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)

                          Probit Regression Results
==============================================================================
Dep. Variable:                   skin   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.03023
Time:                        14:18:27   Log-Likelihood:                -248.59
converged:                       True   LL-Null:                       -256.34
Covariance Type:            nonrobust   LLR p-value:                    0.4885
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0086      0.022     -0.397      0.691      -0.051       0.034
income              -6.22e-06   1.06e-05     -0.588      0.557    -2.7e-05    1.45e-05
n_child                0.0227      0.193      0.118      0.906      -0.356       0.402
type_area              0.0270      0.334      0.081      0.936      -0.628       0.682
invalid                0.1432      0.514      0.279      0.780      -0.863       1.150
visit_doctor           0.1890      0.229      0.825      0.409      -0.260       0.638
work                  -3.0811      1.802     -1.710      0.087      -6.613       0.451
diploma                0.6390      1.586      0.403      0.687      -2.470       3.748
mar_st                -0.4380      1.527     -0.287      0.774      -3.431       2.556
alcohol                2.8371      1.326      2.140      0.032       0.239       5.435
smoking               -1.0770      1.730     -0.622      0.534      -4.468       2.314
phys_active           -0.9798      2.422     -0.405      0.686      -5.727       3.767
diploma_gresid        -0.2837      0.976     -0.291      0.771      -2.197       1.630
mar_st_gresid          0.2415      0.911      0.265      0.791      -1.544       2.027
alcohol_gresid        -1.7228      0.801     -2.152      0.031      -3.292      -0.154
smoking_gresid         0.7232      0.968      0.747      0.455      -1.173       2.620
phys_active_gresid     0.6213      1.408      0.441      0.659      -2.137       3.380
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:               oncology   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                  0.2243
Time:                        14:18:28   Log-Likelihood:                -148.01
converged:                       True   LL-Null:                       -190.81
Covariance Type:            nonrobust   LLR p-value:                 1.601e-11
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0134      0.029      0.455      0.649      -0.044       0.071
income              1.158e-05    1.2e-05      0.967      0.334   -1.19e-05     3.5e-05
n_child               -0.0954      0.263     -0.363      0.717      -0.610       0.420
type_area              0.1099      0.392      0.281      0.779      -0.658       0.878
invalid                2.0117      0.518      3.885      0.000       0.997       3.027
visit_doctor           0.2735      0.277      0.987      0.324      -0.270       0.817
work                  -3.7325      2.371     -1.574      0.115      -8.380       0.915
diploma               -2.0451      1.655     -1.236      0.217      -5.289       1.198
mar_st                 0.5582      1.967      0.284      0.777      -3.297       4.413
alcohol                1.9120      1.461      1.309      0.191      -0.951       4.775
smoking               -1.6878      2.053     -0.822      0.411      -5.712       2.337
phys_active           -1.7854      3.255     -0.548      0.583      -8.165       4.595
diploma_gresid         1.2328      1.018      1.211      0.226      -0.762       3.228
mar_st_gresid         -0.4404      1.181     -0.373      0.709      -2.754       1.873
alcohol_gresid        -1.2956      0.885     -1.465      0.143      -3.029       0.438
smoking_gresid         1.1470      1.128      1.017      0.309      -1.064       3.358
phys_active_gresid     0.9492      1.868      0.508      0.611      -2.711       4.610
======================================================================================
                          Probit Regression Results
==============================================================================
Dep. Variable:         is_health_good   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Mon, 04 May 2026   Pseudo R-squ.:                 0.08951
Time:                        14:18:28   Log-Likelihood:                -1649.4
converged:                       True   LL-Null:                       -1811.6
Covariance Type:            nonrobust   LLR p-value:                 2.308e-59
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0611      0.009     -6.864      0.000      -0.079      -0.044
income              9.831e-06   4.15e-06      2.367      0.018    1.69e-06     1.8e-05
n_child                0.0770      0.074      1.044      0.297      -0.068       0.222
type_area              0.3671      0.134      2.738      0.006       0.104       0.630
invalid               -1.2116      0.363     -3.339      0.001      -1.923      -0.500
visit_doctor          -0.1397      0.092     -1.513      0.130      -0.321       0.041
work                   3.5334      0.747      4.728      0.000       2.069       4.998
diploma               -0.5495      0.604     -0.909      0.363      -1.734       0.635
mar_st                -1.3918      0.605     -2.301      0.021      -2.577      -0.206
alcohol               -0.0194      0.515     -0.038      0.970      -1.030       0.991
smoking                0.0311      0.783      0.040      0.968      -1.504       1.566
phys_active           -1.7572      1.031     -1.704      0.088      -3.779       0.264
diploma_gresid         0.4478      0.371      1.208      0.227      -0.279       1.174
mar_st_gresid          0.7807      0.358      2.178      0.029       0.078       1.483
alcohol_gresid         0.0132      0.315      0.042      0.967      -0.604       0.631
smoking_gresid        -0.0592      0.441     -0.134      0.893      -0.923       0.805
phys_active_gresid     1.0085      0.597      1.690      0.091      -0.161       2.178
======================================================================================

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\discrete\discrete_model.py:530: FutureWarning: linear keyword is deprecated, use which="linear"
  warnings.warn(msg, FutureWarning)
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:1912: FutureWarning: The behavior of wald_test will change after 0.14 to returning scalar test statistic values. To get the future behavior now, set scalar to True. To silence this message while retaining the legacy behavior, set scalar to False.
  warnings.warn(

In [28]:
results

[{'sex': 1,
  'illness': 'heart',
  'coef_diploma': -0.9537989781474785,
  'pval_diploma': 0.4032938199458408,
  'exogeneity_pval': array(0.28812319),
  'n_obs': 1926,
  'pseudo_r2': 0.13703651729654331},
 {'sex': 1,
  'illness': 'lungs',
  'coef_diploma': -1.1566512217387324,
  'pval_diploma': 0.5295797315654724,
  'exogeneity_pval': array(0.01918627),
  'n_obs': 1926,
  'pseudo_r2': 0.061419987909364315},
 {'sex': 1,
  'illness': 'liver',
  'coef_diploma': -0.4687983572606453,
  'pval_diploma': 0.7193601332854489,
  'exogeneity_pval': array(0.99159377),
  'n_obs': 1926,
  'pseudo_r2': 0.08908324028510817},
 {'sex': 1,
  'illness': 'kidneys',
  'coef_diploma': -0.2569281583847186,
  'pval_diploma': 0.8528511245522301,
  'exogeneity_pval': array(0.89618589),
  'n_obs': 1926,
  'pseudo_r2': 0.0525254140583854},
 {'sex': 1,
  'illness': 'stomach',
  'coef_diploma': 0.6142737346018782,
  'pval_diploma': 0.5611516526832124,
  'exogeneity_pval': array(0.47411225),
  'n_obs': 1926,
  'pseudo_r2': 0.036630847004326506},
 {'sex': 1,
  'illness': 'spine',
  'coef_diploma': 1.0052996895834139,
  'pval_diploma': 0.4111777771624959,
  'exogeneity_pval': array(0.72777475),
  'n_obs': 1926,
  'pseudo_r2': 0.05352447390582904},
 {'sex': 1,
  'illness': 'diabetes',
  'coef_diploma': 0.17595053726080898,
  'pval_diploma': 0.9241460085742279,
  'exogeneity_pval': array(0.43240718),
  'n_obs': 1926,
  'pseudo_r2': 0.11677192380038748},
 {'sex': 1,
  'illness': 'hypertension',
  'coef_diploma': 0.11767606132951139,
  'pval_diploma': 0.8963573923676456,
  'exogeneity_pval': array(0.5737786),
  'n_obs': 1926,
  'pseudo_r2': 0.14658189727780835},
 {'sex': 1,
  'illness': 'joints',
  'coef_diploma': 1.267942998168005,
  'pval_diploma': 0.39778223679139757,
  'exogeneity_pval': array(0.01570352),
  'n_obs': 1926,
  'pseudo_r2': 0.1210233089280609},
 {'sex': 1,
  'illness': 'ENT_organs',
  'coef_diploma': 3.387188122776378,
  'pval_diploma': 0.08649702641469117,
  'exogeneity_pval': array(0.00974118),
  'n_obs': 1926,
  'pseudo_r2': 0.06421881487115233},
 {'sex': 1,
  'illness': 'neurology',
  'coef_diploma': 2.9764277131392323,
  'pval_diploma': 0.2287031143035736,
  'exogeneity_pval': array(0.02826381),
  'n_obs': 1926,
  'pseudo_r2': 0.1559818486870026},
 {'sex': 1,
  'illness': 'eyes',
  'coef_diploma': 0.24560840639943862,
  'pval_diploma': 0.8307904379844459,
  'exogeneity_pval': array(0.99453209),
  'n_obs': 1926,
  'pseudo_r2': 0.06051562033229041},
 {'sex': 1,
  'illness': 'allergy',
  'coef_diploma': -0.4110845756739662,
  'pval_diploma': 0.7370561482306972,
  'exogeneity_pval': array(0.81086696),
  'n_obs': 1926,
  'pseudo_r2': 0.028246835568006334},
 {'sex': 1,
  'illness': 'veins',
  'coef_diploma': 0.5554047849401028,
  'pval_diploma': 0.7012362732593365,
  'exogeneity_pval': array(0.8352475),
  'n_obs': 1926,
  'pseudo_r2': 0.07639385991234182},
 {'sex': 1,
  'illness': 'skin',
  'coef_diploma': 2.143656202923585,
  'pval_diploma': 0.19827597820518506,
  'exogeneity_pval': array(0.42377634),
  'n_obs': 1926,
  'pseudo_r2': 0.062338225626039634},
 {'sex': 1,
  'illness': 'oncology',
  'coef_diploma': 6.426116832768243,
  'pval_diploma': 0.13524199600229114,
  'exogeneity_pval': array(0.09416332),
  'n_obs': 1926,
  'pseudo_r2': 0.3454775011739756},
 {'sex': 1,
  'illness': 'is_health_good',
  'coef_diploma': -0.2548953726644167,
  'pval_diploma': 0.7996594645474158,
  'exogeneity_pval': array(0.1559406),
  'n_obs': 1926,
  'pseudo_r2': 0.12685675950766262},
 {'sex': 2,
  'illness': 'heart',
  'coef_diploma': -0.6899089438735388,
  'pval_diploma': 0.5825488025715253,
  'exogeneity_pval': array(0.5271505),
  'n_obs': 2672,
  'pseudo_r2': 0.12605072743865098},
 {'sex': 2,
  'illness': 'lungs',
  'coef_diploma': -0.28824757436266046,
  'pval_diploma': 0.7995125996711239,
  'exogeneity_pval': array(0.35789185),
  'n_obs': 2672,
  'pseudo_r2': 0.059530831175105936},
 {'sex': 2,
  'illness': 'liver',
  'coef_diploma': 0.9430184756681219,
  'pval_diploma': 0.530681448674815,
  'exogeneity_pval': array(0.08938931),
  'n_obs': 2672,
  'pseudo_r2': 0.08348485905424685},
 {'sex': 2,
  'illness': 'kidneys',
  'coef_diploma': -0.634660829036869,
  'pval_diploma': 0.49163239902543565,
  'exogeneity_pval': array(0.4574325),
  'n_obs': 2672,
  'pseudo_r2': 0.04335259903703603},
 {'sex': 2,
  'illness': 'stomach',
  'coef_diploma': -0.05956729721723968,
  'pval_diploma': 0.9347166991360648,
  'exogeneity_pval': array(0.05346344),
  'n_obs': 2672,
  'pseudo_r2': 0.06684352935738114},
 {'sex': 2,
  'illness': 'spine',
  'coef_diploma': 0.6689015273648236,
  'pval_diploma': 0.3969789266724095,
  'exogeneity_pval': array(0.6966614),
  'n_obs': 2672,
  'pseudo_r2': 0.0586679518510399},
 {'sex': 2,
  'illness': 'diabetes',
  'coef_diploma': 1.751876983934121,
  'pval_diploma': 0.07261662164572952,
  'exogeneity_pval': array(0.39582913),
  'n_obs': 2672,
  'pseudo_r2': 0.10830133134584641},
 {'sex': 2,
  'illness': 'hypertension',
  'coef_diploma': 1.4050113510254498,
  'pval_diploma': 0.06426300396356165,
  'exogeneity_pval': array(0.23350995),
  'n_obs': 2672,
  'pseudo_r2': 0.17653454103681032},
 {'sex': 2,
  'illness': 'joints',
  'coef_diploma': 0.5636157159957129,
  'pval_diploma': 0.4934245452586279,
  'exogeneity_pval': array(0.0358678),
  'n_obs': 2672,
  'pseudo_r2': 0.15560793582287458},
 {'sex': 2,
  'illness': 'ENT_organs',
  'coef_diploma': -0.04502381014308846,
  'pval_diploma': 0.9574809622621994,
  'exogeneity_pval': array(0.01460252),
  'n_obs': 2672,
  'pseudo_r2': 0.01811414296208913},
 {'sex': 2,
  'illness': 'neurology',
  'coef_diploma': -0.7540772786843282,
  'pval_diploma': 0.4579406206818559,
  'exogeneity_pval': array(0.55840317),
  'n_obs': 2672,
  'pseudo_r2': 0.07152933127957373},
 {'sex': 2,
  'illness': 'eyes',
  'coef_diploma': -0.22022025821058108,
  'pval_diploma': 0.7639880319344674,
  'exogeneity_pval': array(0.00064824),
  'n_obs': 2672,
  'pseudo_r2': 0.05640163354641348},
 {'sex': 2,
  'illness': 'allergy',
  'coef_diploma': 0.6450833788646877,
  'pval_diploma': 0.4201618808180435,
  'exogeneity_pval': array(0.31088585),
  'n_obs': 2672,
  'pseudo_r2': 0.03956655913604923},
 {'sex': 2,
  'illness': 'veins',
  'coef_diploma': -1.182073113520703,
  'pval_diploma': 0.14064370582692148,
  'exogeneity_pval': array(0.08590597),
  'n_obs': 2672,
  'pseudo_r2': 0.06245991906278603},
 {'sex': 2,
  'illness': 'skin',
  'coef_diploma': 0.6390118280168937,
  'pval_diploma': 0.6870529434321597,
  'exogeneity_pval': array(0.35344461),
  'n_obs': 2672,
  'pseudo_r2': 0.030230265236204756},
 {'sex': 2,
  'illness': 'oncology',
  'coef_diploma': -2.045086019514796,
  'pval_diploma': 0.2165363425703829,
  'exogeneity_pval': array(0.65213442),
  'n_obs': 2672,
  'pseudo_r2': 0.22431894794098994},
 {'sex': 2,
  'illness': 'is_health_good',
  'coef_diploma': -0.5494571689333962,
  'pval_diploma': 0.3632995072467635,
  'exogeneity_pval': array(0.03566036),
  'n_obs': 2672,
  'pseudo_r2': 0.08950924085295331}]