In [5]:
import pyreadstat
df, meta = pyreadstat.read_sav("data/r33iall_84.sav")
df

,idind,ccredid_i,ccid_i,ccid_h,bbid_i,bbid_h,aaid_i,aaid_h,zid_i,zid_h,...,ccl43,ccl43a,ccl43as,ccm96,ccm97,ccm98,ccm99,ccm100,ccm101,ccm111
0,92.0,487801.0,1008401.0,10084.0,1008401.0,10084.0,1008401.0,10084.0,1008401.0,10084.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,108.0,487901.0,1008801.0,10088.0,1008801.0,10088.0,1008801.0,10088.0,1008801.0,10088.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,110.0,485703.0,1009603.0,10096.0,1009603.0,10096.0,1009603.0,10096.0,1009603.0,10096.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,112.0,488001.0,1008901.0,10089.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,125.0,130301.0,1010801.0,10108.0,1010801.0,10108.0,1010801.0,10108.0,1010801.0,10108.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16877,65365.0,285811.0,77002411.0,770024.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16878,65366.0,284504.0,77000404.0,770004.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16879,65367.0,285006.0,77000906.0,770009.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16880,65368.0,285007.0,77000907.0,770009.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,,2.0,1.0,2.0,2.0,2.0,2.0,NaN
16881,65369.0,285008.0,77000908.0,770009.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,,2.0,2.0,2.0,2.0,2.0,2.0,NaN

In [ ]:
dfw = df.copy()

outcome_vars = ["ccm20.61", "ccm20.62", "ccm20.63", "ccm20.64", "ccm20.65", "ccm20.66", "ccm20.620", "ccm20.69",
                "ccm20.610", "ccm20.611", "ccm20.612", "ccm20.613", "ccm20.615", "ccm20.616", "ccm20.617", "ccm20.618",
                "ccm20.614", "ccm20.619", "ccm20.67"]

self_assessment_health = ["ccm3"]

educ = ["cc_diplom"]

control_vars = ["cc_age", "ccj13.2", "ccj72.172", "cch5", "status", "ccm20.7", "cc_marst", "ccl5.0", "ccj1", "ccm80.0", "ccm71", "ccm113a"]

,idind,ccredid_i,ccid_i,ccid_h,bbid_i,bbid_h,aaid_i,aaid_h,zid_i,zid_h,...,ccl43,ccl43a,ccl43as,ccm96,ccm97,ccm98,ccm99,ccm100,ccm101,ccm111
0,92.0,487801.0,1008401.0,10084.0,1008401.0,10084.0,1008401.0,10084.0,1008401.0,10084.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,108.0,487901.0,1008801.0,10088.0,1008801.0,10088.0,1008801.0,10088.0,1008801.0,10088.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,110.0,485703.0,1009603.0,10096.0,1009603.0,10096.0,1009603.0,10096.0,1009603.0,10096.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,112.0,488001.0,1008901.0,10089.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,125.0,130301.0,1010801.0,10108.0,1010801.0,10108.0,1010801.0,10108.0,1010801.0,10108.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16877,65365.0,285811.0,77002411.0,770024.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16878,65366.0,284504.0,77000404.0,770004.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16879,65367.0,285006.0,77000906.0,770009.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16880,65368.0,285007.0,77000907.0,770009.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,,2.0,1.0,2.0,2.0,2.0,2.0,NaN
16881,65369.0,285008.0,77000908.0,770009.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,,2.0,2.0,2.0,2.0,2.0,2.0,NaN